- name: "Move files to server"
  become: true
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu

- name: "install package"
  shell: |
    cd /home/ubuntu/backend
    sudo npm install
- name: "run migrations"
  shell: |
    cd /home/ubuntu/backend
    sudo npm run migrations
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
